apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-blue
  labels:
    app: alert-svc
    version: blue
    env: active
spec:
  replicas: 5
  selector:
    matchLabels:
      app: alert-svc
      version: blue
  template:
    metadata:
      labels:
        app: alert-svc
        version: blue
        env: active
    spec:
      containers:
        - name: alert-svc
          image: chemch/alert-svc:blue
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: "false"