apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-svc
      version: green
  template:
    metadata:
      labels:
        app: alert-svc
        version: green
    spec:
      containers:
        - name: alert-svc
          image: chemch/alert-svc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002