apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-svc
      version: blue
  template:
    metadata:
      labels:
        app: alert-svc
        version: blue
    spec:
      containers:
        - name: alert-svc
          image: 211125540194.dkr.ecr.us-east-1.amazonaws.com/alert-svc:202504260630
          imagePullPolicy: Always
