apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-svc
      version: green
  template:
    metadata:
      labels:
        app: alert-svc
        version: green
    spec:
      containers:
        - name: alert-svc
          image: 211125540194.dkr.ecr.us-east-1.amazonaws.com/alert-svc:dev_202504240507
          imagePullPolicy: Always
