apiVersion: v1
kind: Service
metadata:
  name: alert-svc
spec:
  selector:
    app: alert-svc
    version: green
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP