apiVersion: v1
kind: Service
metadata:
  name: alert-svc
  labels:
    app: alert-svc
spec:
  selector:
    app: alert-svc
  ports:
    - protocol: TCP
      port: 0
      targetPort: 0
  type: ClusterIP