apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: alert-svc
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"