resources:
  - detection-namespace.yaml
  - ../../../base/detection-svc

patches:
  - target:
      kind: Deployment
      name: detection-svc
    path: patch-detection-deployment.yaml

  - target:
      kind: Service
      name: detection-svc
    path: patch-detection-service.yaml

images:
  - name: chemch/detection-svc
    newTag: uat