# argo/observability/tempo.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.21.0
    helm:
      values: |
        service:
          type: ClusterIP

        persistence:
          enabled: false

        tempo:
          metricsGenerator:
            enabled: true
          searchEnabled: true  # Enables trace search in Grafana

        otlp:
          http:
            enabled: true
            port: 4318
          grpc:
            enabled: true
            port: 4317

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true