apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-svc
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: intel-svc
          ports:
            - containerPort: 7008
          env:
            - name: PORT
              value: "7008"