apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-qa
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: alert-svc
          imagePullPolicy: Always
          ports:
            - containerPort: 6002
          env:
            - name: PORT
              value: "6002"