resources:
  - namespace.yaml
  - ../../../base/intel-svc

patches:
  - target:
      kind: Deployment
      name: intel-svc
    path: patch-rollout.yaml

  - target:
      kind: Service
      name: intel-svc
    path: patch-service.yaml

images:
  - name: intel-svc
    newName: 211125540194.dkr.ecr.us-east-1.amazonaws.com/intel-svc
    newTag: prod_202504260336