apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-svc-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chemch/caz-conf.git
    targetRevision: main
    path: overlays/intel-svc/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: intel-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true