apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: alert-svc
          ports:
            - containerPort: 7002
          env:
            - name: PORT
              value: "7002"