apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: detection-svc
spec:
  template:
    spec:
      containers:
        - name: detection-svc
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: DEBUG
              value: "false"