apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intel-svc
  template:
    metadata:
      labels:
        app: intel-svc
    spec:
      containers:
        - name: intel-svc
          image: intel-svc:placeholder
          imagePullPolicy: Always