apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-svc-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chemch/caz-conf.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true