resources:
  - namespace.yaml
  - ../../../base/alert-svc

patches:
  - target:
      kind: Deployment
      name: alert-svc-blue
    path: patch-blue-deployment.yaml

  - target:
      kind: Deployment
      name: alert-svc-green
    path: patch-green-deployment.yaml

  - target:
      kind: Service
      name: alert-svc
    path: patch-service.yaml