resources:
  - alert-namespace.yaml
  - ../../../base/alert-svc

patches:
  - target:
      kind: Deployment
      name: alert-svc
    path: patch-alert-deployment.yaml

  - target:
      kind: Service
      name: alert-svc
    path: patch-alert-service.yaml

images:
  - name: chemch/alert-svc
    newTag: uat