resources:
  - namespace.yaml
  - ../../../base/alert-svc/deployment-blue.yaml
#  - ../../../base/alert-svc/deployment-green.yaml

patches:
  - path: patch-deployment-blue.yaml
    target:
      kind: Deployment
      name: alert-svc-blue
#  - path: patch-deployment-green.yaml
#    target:
#      kind: Deployment
#      name: alert-svc-green
  - path: patch-service.yaml
    target:
      kind: Service
      name: alert-svc

images:
  - name: chemch/alert-svc
    newTag: dev