# overlays/alert-svc/dev/kustomization.yaml
resources:
  - namespace.yaml
  - ../../../base/alert-svc

patches:
  - target:
      kind: Deployment
      name: alert-svc
    path: patch-deployment-blue.yaml

  - target:
      kind: Service
      name: alert-svc
    path: patch-service.yaml

images:
  - name: chemch/alert-svc
    newTag: dev