resources:
  - namespace.yaml
  - ../../../base/alert-svc

patches:
  - target:
      kind: Deployment
      name: alert-svc
    path: patch-deployment.yaml

  - target:
      kind: Service
      name: alert-svc
    path: patch-service.yaml

  - path: disable-deployment-green.yaml

images:
  - name: chemch/alert-svc
    newTag: dev