apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-blue
spec:
  selector:
    matchLabels:
      app: alert-svc
      version: blue
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: alert-svc
          env:
            - name: PORT
              value: "5002"
            - name: DEBUG
              value: "true"