apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-green
spec:
  template:
    metadata:
      labels:
        version: green
    spec:
      containers:
        - name: alert-svc
          env:
            - name: PORT
              value: "5002"
            - name: DEBUG
              value: "true"