resources:
  - namespace.yaml
  - ../../../base/alert-svc
  - rollout.yaml

patches:
  - target:
      kind: Service
      name: alert-svc
    path: patch-service.yaml

images:
  - name: chemch/alert-svc
    newTag: prod