apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-svc-green
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: alert-svc
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"