apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: alert-svc
  namespace: alert-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alert-svc
  template:
    metadata:
      labels:
        app: alert-svc
    spec:
      containers:
        - name: alert-svc
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100