name: Deploy Blue/Green Version Changes

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Target Env (DEV, QA, UAT, PROD)
      service_name:
        required: true
        description: Service
      blue_tag:
        required: false
        description: Image Tag for Blue
      green_tag:
        required: false
        description: Image Tag for Green

jobs:
  update-blue-green:
    name: Update Blue/Green Image Tags
    runs-on: ubuntu-latest
    environment: prod

    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
      SERVICE_NAME: ${{ inputs.service_name || 'alert-svc' }}
      ENVIRONMENT: ${{ inputs.environment || 'prod' }}
      BLUE_TAG: ${{ inputs.blue_tag || '' }}
      GREEN_TAG: ${{ inputs.green_tag || github.event.release.tag_name }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Blue Deployment Image (Overlay Only)
        if: ${{ inputs.blue_tag != '' }}
        run: |
          if [ -f overlays/${{ env.SERVICE_NAME }}/${{ env.ENVIRONMENT }}/patch-blue-deployment.yaml ]; then
            yq eval '(.spec.template.spec.containers[] | select(.name == "${{ env.SERVICE_NAME }}").image) = "211125540194.dkr.ecr.us-east-1.amazonaws.com/${{ env.SERVICE_NAME }}:${{ env.BLUE_TAG }}"' -i overlays/${{ env.SERVICE_NAME }}/${{ env.ENVIRONMENT }}/patch-blue-deployment.yaml
          fi

      - name: Update Green Deployment Image (Overlay Only)
        if: ${{ inputs.green_tag != '' || github.event.release.tag_name }}
        run: |
          if [ -f overlays/${{ env.SERVICE_NAME }}/${{ env.ENVIRONMENT }}/patch-green-deployment.yaml ]; then
            yq eval '(.spec.template.spec.containers[] | select(.name == "${{ env.SERVICE_NAME }}").image) = "211125540194.dkr.ecr.us-east-1.amazonaws.com/${{ env.SERVICE_NAME }}:${{ env.GREEN_TAG }}"' -i overlays/${{ env.SERVICE_NAME }}/${{ env.ENVIRONMENT }}/patch-green-deployment.yaml
          fi

      - name: Commit and Push Changes
        if: ${{ inputs.blue_tag != '' || inputs.green_tag != '' || github.event.release.tag_name }}
        env:
          PAT_PUSH_TOKEN: ${{ secrets.REPO_PAT }}
        run: |
          git remote set-url origin "https://x-access-token:${PAT_PUSH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          git add overlays/${{ env.SERVICE_NAME }}/${{ env.ENVIRONMENT }}/patch-blue-deployment.yaml || true
          git add overlays/${{ env.SERVICE_NAME }}/${{ env.ENVIRONMENT }}/patch-green-deployment.yaml || true
          git diff --quiet && git diff --staged --quiet || git commit -m " $SERVICE_NAME: blue=$BLUE_TAG, green=$GREEN_TAG ($ENVIRONMENT overlay)"
          git push origin HEAD:main