name: Deploy Dev

on:
  repository_dispatch:
    types: [start-dev-deployment]

jobs:
  update-kustomize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caz-conf
        uses: actions/checkout@v3

      - name: Update Dev Overlays
        run: |
          echo "🎯 Platform merged to develop. Time to update conf repo."
