name: Deploy Dev

on:
  repository_dispatch:
    types: [start-dev-deployment]
  workflow_dispatch:

jobs:
  deploy-detection-svc:
    name: Deploy detection-svc to EKS
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

    steps:
      - name: Checkout caz-conf repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$EKS_CLUSTER_NAME"

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh

      - name: Update detection-svc image tag in Kustomize overlay
        run: |
          TAG=${{ github.event.client_payload.tag || 'latest' }}
          echo "Updating image to tag: $TAG"
          ./scripts/set-image.sh detection-svc "$TAG"

      - name: Deploy detection-svc with custom script
        run: ${{ github.workspace }}/scripts/start-service.sh detection-svc dev