name: Dispatch Listener

on:
  repository_dispatch:
    types: [start-deployment]

jobs:
  forward-dispatch:
    uses: ./.github/workflows/deploy-services.yaml
    with:
      environment: ${{ github.event.client_payload.environment }}
      tag: ${{ github.event.client_payload.tag }}
      service_name: ${{ github.event.client_payload.service_name }}
    secrets: inherit