name: Switch Blue/Green Color

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service name (e.g. alert-svc)"
        required: true
      environment:
        description: "Environment (e.g. qa, prod)"
        required: true

jobs:
  switch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false  # 👈 disables the default token auth

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push updated patch-service.yaml with PAT
        env:
          PAT_PUSH_TOKEN: ${{ secrets.CONF_REPO_PAT }}
        run: |
          git remote set-url origin "https://x-access-token:${PAT_PUSH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          git push origin HEAD:main