name: Toggle Blue Green Service Pointer

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service name (e.g. alert-svc)"
        required: true
      environment:
        description: "Environment (e.g. qa, prod)"
        required: true

jobs:
  switch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false

      - name: Set up Git Identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Switch Color - ${{ github.event.inputs.service }} in ${{ github.event.inputs.environment }}
        run: ./scripts/toggle-blue-green.sh ${{ github.event.inputs.service }} ${{ github.event.inputs.environment }}

      - name: Push patch-service.yaml Update
        env:
          PAT_PUSH_TOKEN: ${{ secrets.REPO_PAT }}
        run: |
          git remote set-url origin "https://x-access-token:${PAT_PUSH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          git push origin HEAD:main
