name: Deploy Blue/Green Versions

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Target environment (dev, qa, uat, prod)
      service_name:
        required: true
        description: Service name (e.g., alert-svc)
      blue_tag:
        required: false
        description: Image tag for blue deployment
      green_tag:
        required: false
        description: Image tag for green deployment

jobs:
  update-blue-green:
    name: Update Blue/Green Image Tags
    runs-on: ubuntu-latest
    environment: prod

    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
      SERVICE_NAME: ${{ inputs.service_name || 'alert-svc' }}
      ENVIRONMENT: ${{ inputs.environment || 'prod' }}
      BLUE_TAG: ${{ inputs.blue_tag || 'stable' }}
      GREEN_TAG: ${{ inputs.green_tag || github.event.release.tag_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update blue deployment image
        run: |
          yq eval '(.spec.template.spec.containers[] | select(.name == "${{ env.SERVICE_NAME }}").image) = "211125540194.dkr.ecr.us-east-1.amazonaws.com/${{ env.SERVICE_NAME }}:${{ env.BLUE_TAG }}"' -i base/${{ env.SERVICE_NAME }}/deployment-blue.yaml

      - name: Update green deployment image
        run: |
          yq eval '(.spec.template.spec.containers[] | select(.name == "${{ env.SERVICE_NAME }}").image) = "211125540194.dkr.ecr.us-east-1.amazonaws.com/${{ env.SERVICE_NAME }}:${{ env.GREEN_TAG }}"' -i base/${{ env.SERVICE_NAME }}/deployment-green.yaml

      - name: Commit and Push Changes
        env:
          PAT_PUSH_TOKEN: ${{ secrets.REPO_PAT }}
        run: |
          git remote set-url origin "https://x-access-token:${PAT_PUSH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          git add base/${{ env.SERVICE_NAME }}/deployment-blue.yaml
          git add base/${{ env.SERVICE_NAME }}/deployment-green.yaml
          git commit -m "🚀 $SERVICE_NAME: blue=$BLUE_TAG, green=$GREEN_TAG"
          git push origin HEAD:main
