apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 70.7.0  # Latest as of now
    helm:
      values: |
        alertmanager:
          enabled: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
        nodeExporter:
          enabled: false
        pushgateway:
          enabled: false
        grafana:
          enabled: true
          adminPassword: "changeme"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: "CustomResourceDefinition"
      jsonPointers:
        - /metadata/annotations